# Generated by Django 3.0.7 on 2020-10-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('user_address', models.CharField(max_length=100)),
                ('user_image', models.ImageField(upload_to='upload/<django.db.models.fields.CharField>')),
            ],
        ),
    ]
