# Generated by Django 3.0.7 on 2020-10-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20201025_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='upload/2020-10-30-15-52-37')),
                ('description', models.CharField(max_length=10000)),
                ('weight', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(upload_to='Faces/2020-10-30-15-52-37'),
        ),
    ]
