# Generated by Django 3.0.7 on 2020-11-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_auto_20201116_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(upload_to='Faces/2020-11-16-18-26-28'),
        ),
    ]
